hotkey:
  modifiers:
    - Alt
  key: '`'
menuRevealKey: Alt
activeTabOnShow: lastUsed
lockWindowCenter: true
launchOnStartup: true
startInTray: false
theme: system
hideElements:
  menu: false
  buttonIcons: false
  buttonText: false
  emptyButtons: false
  rowF: false
  row1: false
  row2: false
  row3: false
